{
 "title": "Custo",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Custo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Custo total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(notification_cost_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Custo total por canal",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(notification_cost_total) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Custo médio por notificação",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum(notification_cost_total) / sum(notification_total{status=\"sent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Custo por hora",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(notification_cost_total[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total notificações por canal",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(notification_total[5m])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(notification_total{status=\"sent\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total por canal",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(notification_total{status=\"sent\"}[$__rate_interval])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "Detalhes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "EMAIL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(provider) (increase(notification_total{channel=\"email\", status=\"sent\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUSH",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(provider) (increase(notification_total{channel=\"push\", status=\"sent\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(provider) (increase(notification_total{channel=\"sms\", status=\"sent\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}